%% summary statistics 1.3.5
% 1.option data "data/all_btc33.csv"
% 2.BTC price "data/BTC_USD_Quandl_2015_2022.csv"
% 3.BTC VIX "data/BTC_VIX.csv"
% 4.delete option with prices less than 10
% 5.we use underlying price S_t by median price
% 6.risk free rate rf = 0
% 7.inputs are "all_btc33.csv" from 2020/3/22 to 2022/10/29
% 8.delete observations with extremely low BTC price (less than $2000)
%% load data
clear,clc
option1 = readtable("data/17Jul_18Dec/sampleall.csv");
option2 = readtable("data/deribit20192020/option1920clean.csv");
option3 = readtable("data/all_btc33.csv");
option = [option1;option2;option3];
clear option1 option2 option3
[~,~,~]=mkdir("Summary_stats/1_3_5");

%% delete option if IV==0
option(option.IV<=0,:)=[];
option(option.tau<=0,:)=[];
%% delete options with price < 10
sum(option.option_price<=10)
option = option(option.option_price>10,:);
%% delete observations with extremely low BTC price (less than $2000)
sum(option.BTC_price<1500)
unique(option.date(option.BTC_price<1500))
option(option.BTC_price<1500,:)=[];
%% volume
volume = option.BTC_price .* option.quantity;
moneyness = option.K ./ option.BTC_price - 1;
option = addvars(option, volume, moneyness, 'NewVariableNames',{'volume', 'moneyness'});
volume = option.option_price .* option.quantity;
option = addvars(option, volume, 'NewVariableNames',{'volume_optionprice'});
tau_type = string(option.K);
% for i=1:numel(tau_type)
%     if option.tau(i)<=9
%         tau_type(i)='<=9';
%     elseif option.tau(i)<27
%         tau_type(i)='10_26';
%     elseif option.tau(i)<=33
%         tau_type(i)='27_33';
%     else
%         tau_type(i)='>33';
%     end
% end
tau_type(option.tau<=9)='<=9';
tau_type(option.tau>9 & option.tau<27)='10_26';
tau_type(option.tau>=27 & option.tau<=33)='27_33';
tau_type(option.tau>33)='>33';
option = addvars(option, tau_type, 'NewVariableNames',{'tau_range'});

moneyness_type = tau_type;
moneyness_type(option.moneyness < -0.6)='<-0d6';
moneyness_type(option.moneyness >= -0.6 & option.moneyness <= -0.2)='-0d6_-0d2';
moneyness_type(option.moneyness > -0.2 & option.moneyness < 0.2)='-0d2_0d2';
moneyness_type(option.moneyness >= 0.2 & option.moneyness <= 0.6)='0d2_0d6';
moneyness_type(option.moneyness > 0.6)='>0d6';
option = addvars(option, moneyness_type, 'NewVariableNames',{'moneyness_range'});
clear tau_type moneyness_type volume moneyness
%% Average IV of BTC call options
IV_table = nan(6,5);
IV_table(1,:) = [mean(option.IV(option.moneyness<-0.6 & option.tau<=9 & strcmp(option.putcall,'C'),:)),...
    mean(option.IV(option.moneyness<-0.6 & option.tau>9 & option.tau<=26 & strcmp(option.putcall,'C'),:)),...
    mean(option.IV(option.moneyness<-0.6 & option.tau>=27 & option.tau<=33 & strcmp(option.putcall,'C'),:)),...
    mean(option.IV(option.moneyness<-0.6 & option.tau>33 & strcmp(option.putcall,'C'),:)),...
    mean(option.IV(option.moneyness<-0.6 & strcmp(option.putcall,'C'),:))];
IV_table(2,:) = [mean(option.IV(option.moneyness>=-0.6 & option.moneyness<-0.2 & option.tau<=9 & strcmp(option.putcall,'C'),:)),...
    mean(option.IV(option.moneyness>=-0.6 & option.moneyness<-0.2 & option.tau>9 & option.tau<=26 & strcmp(option.putcall,'C'),:)),...
    mean(option.IV(option.moneyness>=-0.6 & option.moneyness<-0.2 & option.tau>=27 & option.tau<=33 & strcmp(option.putcall,'C'),:)),...
    mean(option.IV(option.moneyness>=-0.6 & option.moneyness<-0.2 & option.tau>33 & strcmp(option.putcall,'C'),:)),...
    mean(option.IV(option.moneyness>=-0.6 & option.moneyness<-0.2 & strcmp(option.putcall,'C'),:))];
IV_table(3,:) = [mean(option.IV(option.moneyness>=-0.2 & option.moneyness<0.2 & option.tau<=9 & strcmp(option.putcall,'C'),:)),...
    mean(option.IV(option.moneyness>=-0.2 & option.moneyness<0.2 & option.tau>9 & option.tau<=26 & strcmp(option.putcall,'C'),:)),...
    mean(option.IV(option.moneyness>=-0.2 & option.moneyness<0.2 & option.tau>=27 & option.tau<=33 & strcmp(option.putcall,'C'),:)),...
    mean(option.IV(option.moneyness>=-0.2 & option.moneyness<0.2 & option.tau>33 & strcmp(option.putcall,'C'),:)),...
    mean(option.IV(option.moneyness>=-0.2 & option.moneyness<0.2 & strcmp(option.putcall,'C'),:))];
IV_table(4,:) = [mean(option.IV(option.moneyness>=0.2 & option.moneyness<0.6 & option.tau<=9 & strcmp(option.putcall,'C'),:)),...
    mean(option.IV(option.moneyness>=0.2 & option.moneyness<0.6 & option.tau>9 & option.tau<=26 & strcmp(option.putcall,'C'),:)),...
    mean(option.IV(option.moneyness>=0.2 & option.moneyness<0.6 & option.tau>=27 & option.tau<=33 & strcmp(option.putcall,'C'),:)),...
    mean(option.IV(option.moneyness>=0.2 & option.moneyness<0.6 & option.tau>33 & strcmp(option.putcall,'C'),:)),...
    mean(option.IV(option.moneyness>=0.2 & option.moneyness<0.6 & strcmp(option.putcall,'C'),:))];
IV_table(5,:) = [mean(option.IV(option.moneyness>=0.6 & option.tau<=9 & strcmp(option.putcall,'C'),:)),...
    mean(option.IV(option.moneyness>=0.6 & option.tau>9 & option.tau<=26 & strcmp(option.putcall,'C'),:)),...
    mean(option.IV(option.moneyness>=0.6 & option.tau>=27 & option.tau<=33 & strcmp(option.putcall,'C'),:)),...
    mean(option.IV(option.moneyness>=0.6 & option.tau>33 & strcmp(option.putcall,'C'),:)),...
    mean(option.IV(option.moneyness>=0.6 & strcmp(option.putcall,'C'),:))];
IV_table(6,:) = [mean(option.IV(option.tau<=9 & strcmp(option.putcall,'C'),:)),...
    mean(option.IV(option.tau>9 & option.tau<=26 & strcmp(option.putcall,'C'),:)),...
    mean(option.IV(option.tau>=27 & option.tau<=33 & strcmp(option.putcall,'C'),:)),...
    mean(option.IV(option.tau>33 & strcmp(option.putcall,'C'),:)),...
    mean(option.IV(strcmp(option.putcall,'C'),:))];
IV_table = IV_table/100;
clear info;
info.rnames = strvcat('.','(0,-0.6)','[-0.6,-0.2)','[-0.2,0.2)','[0.2,0.6)','>0.6','Average');
info.cnames = strvcat('(0,9]','(9,26]','[27,33]','>33','Average');
info.fmt    = '%10.2f';
mprint(IV_table,info)
writetable(table(IV_table),"Summary_stats/1_3_5/Average_IV_call.csv")
%% Average IV of BTC put options
IV_table = nan(6,5);
IV_table(1,:) = [mean(option.IV(option.moneyness<-0.6 & option.tau<=9 & strcmp(option.putcall,'P'),:)),...
    mean(option.IV(option.moneyness<-0.6 & option.tau>9 & option.tau<=26 & strcmp(option.putcall,'P'),:)),...
    mean(option.IV(option.moneyness<-0.6 & option.tau>=27 & option.tau<=33 & strcmp(option.putcall,'P'),:)),...
    mean(option.IV(option.moneyness<-0.6 & option.tau>33 & strcmp(option.putcall,'P'),:)),...
    mean(option.IV(option.moneyness<-0.6 & strcmp(option.putcall,'P'),:))];
IV_table(2,:) = [mean(option.IV(option.moneyness>=-0.6 & option.moneyness<-0.2 & option.tau<=9 & strcmp(option.putcall,'P'),:)),...
    mean(option.IV(option.moneyness>=-0.6 & option.moneyness<-0.2 & option.tau>9 & option.tau<=26 & strcmp(option.putcall,'P'),:)),...
    mean(option.IV(option.moneyness>=-0.6 & option.moneyness<-0.2 & option.tau>=27 & option.tau<=33 & strcmp(option.putcall,'P'),:)),...
    mean(option.IV(option.moneyness>=-0.6 & option.moneyness<-0.2 & option.tau>33 & strcmp(option.putcall,'P'),:)),...
    mean(option.IV(option.moneyness>=-0.6 & option.moneyness<-0.2 & strcmp(option.putcall,'P'),:))];
IV_table(3,:) = [mean(option.IV(option.moneyness>=-0.2 & option.moneyness<0.2 & option.tau<=9 & strcmp(option.putcall,'P'),:)),...
    mean(option.IV(option.moneyness>=-0.2 & option.moneyness<0.2 & option.tau>9 & option.tau<=26 & strcmp(option.putcall,'P'),:)),...
    mean(option.IV(option.moneyness>=-0.2 & option.moneyness<0.2 & option.tau>=27 & option.tau<=33 & strcmp(option.putcall,'P'),:)),...
    mean(option.IV(option.moneyness>=-0.2 & option.moneyness<0.2 & option.tau>33 & strcmp(option.putcall,'P'),:)),...
    mean(option.IV(option.moneyness>=-0.2 & option.moneyness<0.2 & strcmp(option.putcall,'P'),:))];
IV_table(4,:) = [mean(option.IV(option.moneyness>=0.2 & option.moneyness<0.6 & option.tau<=9 & strcmp(option.putcall,'P'),:)),...
    mean(option.IV(option.moneyness>=0.2 & option.moneyness<0.6 & option.tau>9 & option.tau<=26 & strcmp(option.putcall,'P'),:)),...
    mean(option.IV(option.moneyness>=0.2 & option.moneyness<0.6 & option.tau>=27 & option.tau<=33 & strcmp(option.putcall,'P'),:)),...
    mean(option.IV(option.moneyness>=0.2 & option.moneyness<0.6 & option.tau>33 & strcmp(option.putcall,'P'),:)),...
    mean(option.IV(option.moneyness>=0.2 & option.moneyness<0.6 & strcmp(option.putcall,'P'),:))];
IV_table(5,:) = [mean(option.IV(option.moneyness>=0.6 & option.tau<=9 & strcmp(option.putcall,'P'),:)),...
    mean(option.IV(option.moneyness>=0.6 & option.tau>9 & option.tau<=26 & strcmp(option.putcall,'P'),:)),...
    mean(option.IV(option.moneyness>=0.6 & option.tau>=27 & option.tau<=33 & strcmp(option.putcall,'P'),:)),...
    mean(option.IV(option.moneyness>=0.6 & option.tau>33 & strcmp(option.putcall,'P'),:)),...
    mean(option.IV(option.moneyness>=0.6 & strcmp(option.putcall,'P'),:))];
IV_table(6,:) = [mean(option.IV(option.tau<=9 & strcmp(option.putcall,'P'),:)),...
    mean(option.IV(option.tau>9 & option.tau<=26 & strcmp(option.putcall,'P'),:)),...
    mean(option.IV(option.tau>=27 & option.tau<=33 & strcmp(option.putcall,'P'),:)),...
    mean(option.IV(option.tau>33 & strcmp(option.putcall,'P'),:)),...
    mean(option.IV(strcmp(option.putcall,'P'),:))];
IV_table = IV_table/100;
clear info;
info.rnames = strvcat('.','(0,-0.6)','[-0.6,-0.2)','[-0.2,0.2)','[0.2,0.6)','>0.6','Average');
info.cnames = strvcat('(0,9]','(9,26]','[27,33]','>33','Average');
info.fmt    = '%10.2f';
mprint(IV_table,info)
writetable(table(IV_table),"Summary_stats/1_3_5/Average_IV_put.csv")
%% summary statistics: number of observations
%% Call options
Obser_table = nan(6,5);
Obser_table(1,:) = [sum(option.moneyness<-0.6 & option.tau<=9 & strcmp(option.putcall,'C') ),...
    sum(option.moneyness<-0.6 & option.tau>9 & option.tau<=26 & strcmp(option.putcall,'C') ),...
    sum(option.moneyness<-0.6 & option.tau>=27 & option.tau<=33 & strcmp(option.putcall,'C') ),...
    sum(option.moneyness<-0.6 & option.tau>33 & strcmp(option.putcall,'C') ),...
    sum(option.moneyness<-0.6 & strcmp(option.putcall,'C') )];
Obser_table(2,:) = [sum(option.moneyness>=-0.6 & option.moneyness<-0.2 & option.tau<=9 & strcmp(option.putcall,'C') ),...
    sum(option.moneyness>=-0.6 & option.moneyness<-0.2 & option.tau>9 & option.tau<=26 & strcmp(option.putcall,'C') ),...
    sum(option.moneyness>=-0.6 & option.moneyness<-0.2 & option.tau>=27 & option.tau<=33 & strcmp(option.putcall,'C') ),...
    sum(option.moneyness>=-0.6 & option.moneyness<-0.2 & option.tau>33 & strcmp(option.putcall,'C') ),...
    sum(option.moneyness>=-0.6 & option.moneyness<-0.2 & strcmp(option.putcall,'C') )];
Obser_table(3,:) = [sum(option.moneyness>=-0.2 & option.moneyness<0.2 & option.tau<=9 & strcmp(option.putcall,'C') ),...
    sum(option.moneyness>=-0.2 & option.moneyness<0.2 & option.tau>9 & option.tau<=26 & strcmp(option.putcall,'C') ),...
    sum(option.moneyness>=-0.2 & option.moneyness<0.2 & option.tau>=27 & option.tau<=33 & strcmp(option.putcall,'C') ),...
    sum(option.moneyness>=-0.2 & option.moneyness<0.2 & option.tau>33 & strcmp(option.putcall,'C') ),...
    sum(option.moneyness>=-0.2 & option.moneyness<0.2 & strcmp(option.putcall,'C') )];
Obser_table(4,:) = [sum(option.moneyness>=0.2 & option.moneyness<0.6 & option.tau<=9 & strcmp(option.putcall,'C') ),...
    sum(option.moneyness>=0.2 & option.moneyness<0.6 & option.tau>9 & option.tau<=26 & strcmp(option.putcall,'C') ),...
    sum(option.moneyness>=0.2 & option.moneyness<0.6 & option.tau>=27 & option.tau<=33 & strcmp(option.putcall,'C') ),...
    sum(option.moneyness>=0.2 & option.moneyness<0.6 & option.tau>33 & strcmp(option.putcall,'C') ),...
    sum(option.moneyness>=0.2 & option.moneyness<0.6 & strcmp(option.putcall,'C') )];
Obser_table(5,:) = [sum(option.moneyness>=0.6 & option.tau<=9 & strcmp(option.putcall,'C') ),...
    sum(option.moneyness>=0.6 & option.tau>9 & option.tau<=26 & strcmp(option.putcall,'C') ),...
    sum(option.moneyness>=0.6 & option.tau>=27 & option.tau<=33 & strcmp(option.putcall,'C') ),...
    sum(option.moneyness>=0.6 & option.tau>33 & strcmp(option.putcall,'C') ),...
    sum(option.moneyness>=0.6 & strcmp(option.putcall,'C') )];
Obser_table(6,:) = [sum(option.tau<=9 & strcmp(option.putcall,'C') ),...
    sum(option.tau>9 & option.tau<=26 & strcmp(option.putcall,'C') ),...
    sum(option.tau>=27 & option.tau<=33 & strcmp(option.putcall,'C') ),...
    sum(option.tau>33 & strcmp(option.putcall,'C') ),...
    sum(strcmp(option.putcall,'C') )];
clear info;
info.rnames = strvcat('.','(0,-0.6)','[-0.6,-0.2)','[-0.2,0.2)','[0.2,0.6)','>0.6','Average');
info.cnames = strvcat('(0,9]','(9,26]','[27,33]','>33','Average');
info.fmt    = '%10.0f';
mprint(Obser_table,info)
writetable(table(Obser_table),"Summary_stats/1_3_5/Observation_call.csv")
%% Put options
Obser_table = nan(6,5);
Obser_table(1,:) = [sum(option.moneyness<-0.6 & option.tau<=9 & strcmp(option.putcall, 'P') ),...
    sum(option.moneyness<-0.6 & option.tau>9 & option.tau<=26 & strcmp(option.putcall, 'P') ),...
    sum(option.moneyness<-0.6 & option.tau>=27 & option.tau<=33 & strcmp(option.putcall, 'P') ),...
    sum(option.moneyness<-0.6 & option.tau>33 & strcmp(option.putcall, 'P') ),...
    sum(option.moneyness<-0.6 & strcmp(option.putcall, 'P') )];
Obser_table(2,:) = [sum(option.moneyness>=-0.6 & option.moneyness<-0.2 & option.tau<=9 & strcmp(option.putcall, 'P') ),...
    sum(option.moneyness>=-0.6 & option.moneyness<-0.2 & option.tau>9 & option.tau<=26 & strcmp(option.putcall, 'P') ),...
    sum(option.moneyness>=-0.6 & option.moneyness<-0.2 & option.tau>=27 & option.tau<=33 & strcmp(option.putcall, 'P') ),...
    sum(option.moneyness>=-0.6 & option.moneyness<-0.2 & option.tau>33 & strcmp(option.putcall, 'P') ),...
    sum(option.moneyness>=-0.6 & option.moneyness<-0.2 & strcmp(option.putcall, 'P') )];
Obser_table(3,:) = [sum(option.moneyness>=-0.2 & option.moneyness<0.2 & option.tau<=9 & strcmp(option.putcall, 'P') ),...
    sum(option.moneyness>=-0.2 & option.moneyness<0.2 & option.tau>9 & option.tau<=26 & strcmp(option.putcall, 'P') ),...
    sum(option.moneyness>=-0.2 & option.moneyness<0.2 & option.tau>=27 & option.tau<=33 & strcmp(option.putcall, 'P') ),...
    sum(option.moneyness>=-0.2 & option.moneyness<0.2 & option.tau>33 & strcmp(option.putcall, 'P') ),...
    sum(option.moneyness>=-0.2 & option.moneyness<0.2 & strcmp(option.putcall, 'P') )];
Obser_table(4,:) = [sum(option.moneyness>=0.2 & option.moneyness<0.6 & option.tau<=9 & strcmp(option.putcall, 'P') ),...
    sum(option.moneyness>=0.2 & option.moneyness<0.6 & option.tau>9 & option.tau<=26 & strcmp(option.putcall, 'P') ),...
    sum(option.moneyness>=0.2 & option.moneyness<0.6 & option.tau>=27 & option.tau<=33 & strcmp(option.putcall, 'P') ),...
    sum(option.moneyness>=0.2 & option.moneyness<0.6 & option.tau>33 & strcmp(option.putcall, 'P') ),...
    sum(option.moneyness>=0.2 & option.moneyness<0.6 & strcmp(option.putcall, 'P') )];
Obser_table(5,:) = [sum(option.moneyness>=0.6 & option.tau<=9 & strcmp(option.putcall, 'P') ),...
    sum(option.moneyness>=0.6 & option.tau>9 & option.tau<=26 & strcmp(option.putcall, 'P') ),...
    sum(option.moneyness>=0.6 & option.tau>=27 & option.tau<=33 & strcmp(option.putcall, 'P') ),...
    sum(option.moneyness>=0.6 & option.tau>33 & strcmp(option.putcall, 'P') ),...
    sum(option.moneyness>=0.6 & strcmp(option.putcall, 'P') )];
Obser_table(6,:) = [sum(option.tau<=9 & strcmp(option.putcall, 'P') ),...
    sum(option.tau>9 & option.tau<=26 & strcmp(option.putcall, 'P') ),...
    sum(option.tau>=27 & option.tau<=33 & strcmp(option.putcall, 'P') ),...
    sum(option.tau>33 & strcmp(option.putcall, 'P') ),...
    sum(strcmp(option.putcall, 'P') )];
clear info;
info.rnames = strvcat('.','(0,-0.6)','[-0.6,-0.2)','[-0.2,0.2)','[0.2,0.6)','>0.6','Average');
info.cnames = strvcat('(0,9]','(9,26]','[27,33]','>33','Average');
info.fmt    = '%10.0f';
mprint(Obser_table,info)
writetable(table(Obser_table),"Summary_stats/1_3_5/Observation_call.csv")